___
# Final Project - Baseline Model
 

## Imports
** Import pandas, numpy, matplotlib,and seaborn.**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

## Get the Data



In [2]:
data = pd.read_csv("Construction_Permits_in_2020.csv")

*Check the head of data, and check out its info() and describe() methods.**

In [3]:
data.shape

(21522, 34)

In [4]:
data.head()

X          Y  OBJECTID         APPLICATIONDATE ISEXCAVATION  \
0 -76.955760  38.895931  90855698  2020/01/10 12:17:46+00            T   
1 -77.006316  38.906668  90855699  2019/12/26 14:16:46+00            T   
2 -76.993523  38.837742  90856000  2019/09/16 13:38:08+00            F   
3 -77.043455  38.904708  90856194  2019/04/27 15:08:40+00            F   
4 -76.998446  38.904071  90856195  2019/04/27 15:10:44+00            F   

  ISFIXTURE ISPAVING ISLANDSCAPING ISPROJECTIONS ISPSRENTAL  ...  \
0         F        F             F             F          F  ...   
1         F        F             F             F          F  ...   
2         F        F             F             F          F  ...   
3         T        F             F             F          F  ...   
4         T        F             F             F          F  ...   

       READYFORREVIEWDATE            APPLICANTCOMPANYNAME   LATITUDE  \
0  2020/01/10 12:19:02+00  Potomac Electric Power Company  38.895923   
1  2020/01/02 18:33:26+00   DFM Development Services, LLC  38.906660   
2  2019/09/16 13:38:56+00  Potomac Electric Power Company  38.837734   
3  2019/04/29 19:27:05+00    Crown Castle NG Atlantic LLC  38.904700   
4  2019/04/29 19:21:25+00    Crown Castle NG Atlantic LLC  38.904063   

   LONGITUDE GIS_ID                                GLOBALID  CREATOR  CREATED  \
0 -76.955757    NaN  {D18A7D09-8F82-5BE0-E053-792F520A847C}      NaN      NaN   
1 -77.006314    NaN  {D18A7D09-8F83-5BE0-E053-792F520A847C}      NaN      NaN   
2 -76.993521    NaN  {D18A7D09-90B0-5BE0-E053-792F520A847C}      NaN      NaN   
3 -77.043453    NaN  {D18A7D09-9172-5BE0-E053-792F520A847C}      NaN      NaN   
4 -76.998444    NaN  {D18A7D09-9173-5BE0-E053-792F520A847C}      NaN      NaN   

  EDITOR EDITED  
0    NaN    NaN  
1    NaN    NaN  
2    NaN    NaN  
3    NaN    NaN  
4    NaN    NaN  

[5 rows x 34 columns]

In [5]:
data.describe()

X             Y      OBJECTID  TRACKINGNUMBER  \
count  21522.000000  21522.000000  2.152200e+04    21522.000000   
mean     -77.013002     38.911776  9.097569e+07   351937.877799   
std        0.037559      0.029650  2.778327e+04     8162.371864   
min      -77.113391     38.813658  9.085570e+07   199050.000000   
25%      -77.034825     38.895653  9.097633e+07   346631.250000   
50%      -77.014690     38.910532  9.098181e+07   352306.500000   
75%      -76.989416     38.930827  9.098744e+07   358300.750000   
max      -76.910140     38.993526  9.101347e+07   372573.000000   

              XCOORD         YCOORD      LATITUDE     LONGITUDE  GIS_ID  \
count   21522.000000   21522.000000  21522.000000  21522.000000     0.0   
mean   398873.165977  138212.395414     38.911768    -77.013000     NaN   
std      3257.300412    3291.593235      0.029650      0.037559     NaN   
min    390168.990000  127319.990000     38.813651    -77.113389     NaN   
25%    396979.900000  136423.970000     38.895645    -77.034823     NaN   
50%    398726.550000  138074.250000     38.910524    -77.014688     NaN   
75%    400918.417500  140327.082500     38.930819    -76.989414     NaN   
max    407795.708421  147287.490000     38.993518    -76.910138     NaN   

       CREATOR  CREATED  EDITOR  EDITED  
count      0.0      0.0     0.0     0.0  
mean       NaN      NaN     NaN     NaN  
std        NaN      NaN     NaN     NaN  
min        NaN      NaN     NaN     NaN  
25%        NaN      NaN     NaN     NaN  
50%        NaN      NaN     NaN     NaN  
75%        NaN      NaN     NaN     NaN  
max        NaN      NaN     NaN     NaN

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21522 entries, 0 to 21521
Data columns (total 34 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   X                     21522 non-null  float64
 1   Y                     21522 non-null  float64
 2   OBJECTID              21522 non-null  int64  
 3   APPLICATIONDATE       21522 non-null  object 
 4   ISEXCAVATION          21522 non-null  object 
 5   ISFIXTURE             21522 non-null  object 
 6   ISPAVING              21522 non-null  object 
 7   ISLANDSCAPING         21522 non-null  object 
 8   ISPROJECTIONS         21522 non-null  object 
 9   ISPSRENTAL            21522 non-null  object 
 10  TRACKINGNUMBER        21522 non-null  int64  
 11  PERMITNUMBER          17638 non-null  object 
 12  INTAKEDATE            21522 non-null  object 
 13  ISSUEDATE             17638 non-null  object 
 14  EFFECTIVEDATE         21522 non-null  object 
 15  EXPIRATIONDATE     

##### checking the  unique values in status

In [7]:
data['STATUS'].unique()

array(['Permit Expired', 'Cancel/Withdrawn', 'Denied',
       'Approved (Pending Payment)', 'Resubmitted', 'Assigned',
       'Revise and Resubmit', 'Issued', 'Reopened', 'Revoked',
       'Pending Assignment', 'Suspended'], dtype=object)

## Exploratory Data Analysis



In [8]:
data['STATUS'].value_counts()

Permit Expired                17187
Cancel/Withdrawn               2812
Issued                          434
Approved (Pending Payment)      413
Revise and Resubmit             357
Denied                          226
Assigned                         49
Reopened                         15
Resubmitted                      12
Suspended                         8
Revoked                           6
Pending Assignment                3
Name: STATUS, dtype: int64

In [9]:
##### 

In [10]:
values = ['Assigned' , 'Reopened' , 'Resubmitted' , 'Suspended' , 'Revoked' , 'Pending Assignment']
data = data[data.STATUS.isin(values) == False]
data.shape


(21429, 34)

In [11]:
col_list = data.columns
data[col_list].isnull().sum()

X                           0
Y                           0
OBJECTID                    0
APPLICATIONDATE             0
ISEXCAVATION                0
ISFIXTURE                   0
ISPAVING                    0
ISLANDSCAPING               0
ISPROJECTIONS               0
ISPSRENTAL                  0
TRACKINGNUMBER              0
PERMITNUMBER             3808
INTAKEDATE                  0
ISSUEDATE                3808
EFFECTIVEDATE               0
EXPIRATIONDATE              0
XCOORD                      0
YCOORD                      0
STATUS                      0
WLFULLADDRESS               0
PERMITTEENAME             347
OWNERNAME                1739
CONTRACTORNAME          18043
WORKDETAIL                  0
READYFORREVIEWDATE        517
APPLICANTCOMPANYNAME     4422
LATITUDE                    0
LONGITUDE                   0
GIS_ID                  21429
GLOBALID                    0
CREATOR                 21429
CREATED                 21429
EDITOR                  21429
EDITED    

### Dropping non imputable columns , unique values and date columns

In [12]:
print('Current rows and columns', data.shape)
data.drop(['EDITED' , 'EDITOR' , 'CREATOR' , 'CREATED' ,
           'CONTRACTORNAME' , 'PERMITTEENAME' , 'OWNERNAME',
           'APPLICANTCOMPANYNAME' , 'GIS_ID']  , axis = 1, inplace = True)

data.drop(['PERMITNUMBER' , 'ISSUEDATE' , 'READYFORREVIEWDATE']  , axis = 1, inplace = True)
print('shape after NA columns and non imputable columns', data.shape)

Current rows and columns (21429, 34)
shape after NA columns and non imputable columns (21429, 22)


In [13]:
data.drop(['OBJECTID']  , axis = 1, inplace = True)

In [14]:
data.shape

(21429, 21)

In [15]:
xmin = -77.119759
ymin = 38.791645
xmax = -76.909395
ymax = 38.99511
#Exploring Latitude and Longitude
#we'll remove all rows outside of this range

print('Current rows:', data.shape[0])
data = data[(((data.LATITUDE >= -77.119759) & (data.LONGITUDE <= 38.791645)) | 
            ((data.LONGITUDE <= -76.909395) & (data.LONGITUDE >= 38.99511)))]
print('Rows after removing out of box points:', data.shape[0])

Current rows: 21429
Rows after removing out of box points: 21429


In [16]:
numbers=['X', 'Y', 'TRACKINGNUMBER' , 'XCOORD', 'YCOORD',
        'LATITUDE', 'LONGITUDE']
categories=['ISEXCAVATION', 'ISFIXTURE', 'ISPAVING',
       'ISLANDSCAPING', 'ISPROJECTIONS', 'ISPSRENTAL',]
label = ['STATUS']

In [17]:
data['APPLICATIONDATE'] = data['APPLICATIONDATE'].astype(str).str[0:8]
data['APPLICATIONDATE'] = pd.to_datetime(data['APPLICATIONDATE'],  format = '%Y/%m/%d', errors = 'coerce')
data['EXPIRATIONDATE'] = data['EXPIRATIONDATE'].astype(str).str[0:8]
data['EXPIRATIONDATE'] = pd.to_datetime(data['EXPIRATIONDATE'],  format = '%Y/%m/%d', errors = 'coerce')
data['EFFECTIVEDATE'] = data['EFFECTIVEDATE'].astype(str).str[0:8]
data['EFFECTIVEDATE'] = pd.to_datetime(data['EFFECTIVEDATE'],  format = '%Y/%m/%d', errors = 'coerce')
data['INTAKEDATE'] = data['INTAKEDATE'].astype(str).str[0:8]
data['INTAKEDATE'] = pd.to_datetime(data['INTAKEDATE'],  format = '%Y/%m/%d', errors = 'coerce')

data.drop(['APPLICATIONDATE', 'EXPIRATIONDATE' , 'EFFECTIVEDATE' , 'INTAKEDATE'] , axis = 1, inplace = True)
data.drop(['WLFULLADDRESS' , 'WORKDETAIL' , 'GLOBALID'] , axis = 1, inplace = True)

In [18]:
X=data.drop(['STATUS'],axis=1)
y=data['STATUS']
data.head()

X          Y ISEXCAVATION ISFIXTURE ISPAVING ISLANDSCAPING  \
0 -76.955760  38.895931            T         F        F             F   
1 -77.006316  38.906668            T         F        F             F   
2 -76.993523  38.837742            F         F        F             F   
3 -77.043455  38.904708            F         T        F             F   
4 -76.998446  38.904071            F         T        F             F   

  ISPROJECTIONS ISPSRENTAL  TRACKINGNUMBER        XCOORD         YCOORD  \
0             F          F          345089  403837.99000  136453.640000   
1             F          F          344234  399452.38000  137644.650000   
2             F          F          337597  400562.52659  129993.364918   
3             F          F          330462  396230.99000  137427.940000   
4             F          F          330463  400134.98000  137356.320000   

             STATUS   LATITUDE  LONGITUDE  
0    Permit Expired  38.895923 -76.955757  
1    Permit Expired  38.906660 -77.006314  
2    Permit Expired  38.837734 -76.993521  
3  Cancel/Withdrawn  38.904700 -77.043453  
4  Cancel/Withdrawn  38.904063 -76.998444

In [19]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.pipeline import Pipeline
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder , LabelEncoder
from sklearn.preprocessing import StandardScaler

In [20]:
le =LabelEncoder()
y = le.fit_transform(y)

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=1)
print(f'Training examples: {X_train.shape[0]}')
print(f'Test examples: {X_test.shape[0]}')

Training examples: 12857
Test examples: 8572


In [22]:
data.head(5)

X          Y ISEXCAVATION ISFIXTURE ISPAVING ISLANDSCAPING  \
0 -76.955760  38.895931            T         F        F             F   
1 -77.006316  38.906668            T         F        F             F   
2 -76.993523  38.837742            F         F        F             F   
3 -77.043455  38.904708            F         T        F             F   
4 -76.998446  38.904071            F         T        F             F   

  ISPROJECTIONS ISPSRENTAL  TRACKINGNUMBER        XCOORD         YCOORD  \
0             F          F          345089  403837.99000  136453.640000   
1             F          F          344234  399452.38000  137644.650000   
2             F          F          337597  400562.52659  129993.364918   
3             F          F          330462  396230.99000  137427.940000   
4             F          F          330463  400134.98000  137356.320000   

             STATUS   LATITUDE  LONGITUDE  
0    Permit Expired  38.895923 -76.955757  
1    Permit Expired  38.906660 -77.006314  
2    Permit Expired  38.837734 -76.993521  
3  Cancel/Withdrawn  38.904700 -77.043453  
4  Cancel/Withdrawn  38.904063 -76.998444

In [23]:
from sklearn.pipeline import Pipeline
numerical_pipeline = Pipeline([('impute_missing', SimpleImputer(missing_values = np.nan ,strategy='mean')),
                           ('standardize_num', StandardScaler())])

categorical_pipeline = Pipeline([('impute_missing_cats', SimpleImputer(missing_values = np.nan , strategy='most_frequent')),
                          ('create_dummies_cats', OneHotEncoder(handle_unknown='ignore',  sparse=False))])

processing_pipeline = ColumnTransformer(transformers=[('proc_numeric', numerical_pipeline, numbers),
                                                      ('create_dummies', categorical_pipeline, categories)
                                                      ])

In [24]:
p1 = Pipeline([('processing', processing_pipeline),
               ('logreg', LogisticRegression())])

p2 = Pipeline([('processing', processing_pipeline),
               ('tree', DecisionTreeClassifier())])

p3 = Pipeline([('processing', processing_pipeline),
               ('svc', SVC())])

labs = ['Logistic Regression', 'Decision Tree', 'SVM']
clfs = [p1, p2, p3]
clfs = zip(labs, clfs)

In [25]:
modell= p3.fit(X_train, y_train)

In [26]:
from sklearn.metrics import confusion_matrix
y_test_pred = modell.predict(X_test)
print(confusion_matrix(y_test, y_test_pred))

[[   0    7    0    0  169    0]
 [   0  739    0    9  387    0]
 [   0    8    0    0   85    0]
 [   0   14    0   82   79    0]
 [   0  131    0   17 6713    0]
 [   0   23    0    8  101    0]]


In [27]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_test_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       176
           1       0.80      0.65      0.72      1135
           2       0.00      0.00      0.00        93
           3       0.71      0.47      0.56       175
           4       0.89      0.98      0.93      6861
           5       0.00      0.00      0.00       132

    accuracy                           0.88      8572
   macro avg       0.40      0.35      0.37      8572
weighted avg       0.83      0.88      0.85      8572



C:\Users\ASUS\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [28]:
X.head(5)

X          Y ISEXCAVATION ISFIXTURE ISPAVING ISLANDSCAPING  \
0 -76.955760  38.895931            T         F        F             F   
1 -77.006316  38.906668            T         F        F             F   
2 -76.993523  38.837742            F         F        F             F   
3 -77.043455  38.904708            F         T        F             F   
4 -76.998446  38.904071            F         T        F             F   

  ISPROJECTIONS ISPSRENTAL  TRACKINGNUMBER        XCOORD         YCOORD  \
0             F          F          345089  403837.99000  136453.640000   
1             F          F          344234  399452.38000  137644.650000   
2             F          F          337597  400562.52659  129993.364918   
3             F          F          330462  396230.99000  137427.940000   
4             F          F          330463  400134.98000  137356.320000   

    LATITUDE  LONGITUDE  
0  38.895923 -76.955757  
1  38.906660 -77.006314  
2  38.837734 -76.993521  
3  38.904700 -77.043453  
4  38.904063 -76.998444